image: gitlab.codethink.co.uk:5000/infrastructure/python-black-formatter:master

stages:
  - format_checks
  - tests

black:
  stage: format_checks
  script:
    - |
      git rev-list origin/master..HEAD -- | while read commit
      do
        git checkout $commit
        black --check ./
      done

pylint:
  stage: format_checks
  script:
    - |
      python3 -m pip install . pylint pyyaml
      pylint lifecycle

run_tests:
  stage: tests
  script:
    - |
      python3 -m pip install . pytest pyyaml
      pytest
