image: gitlab.codethink.co.uk:5000/infrastructure/python-black-formatter:master

stages:
  - all_checks

format_check:
  stage: all_checks
  script:
    - |
      git rev-list origin/master..HEAD -- | while read commit
      do
        git checkout $commit
        black --check ./
      done

run_tests:
  stage: all_checks
  script:
    - |
      python3 -m pip install pipenv
      pipenv install --dev --system
      export PYTHONPATH="$PYTHONPATH:."
      pytest tests/*.py
