name: Run Test Suite

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # checkout full tree
        fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[dev]
    - name: Testing the code with pytest
      run: pytest
  smoketest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # checkout full tree
        fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Make sure lifecycle can be installed and run using pipenv
      run: |
        python -m pip install pipenv
        pipenv install --skip-lock
        pipenv run lifecycle --help
