name: Run Test Suite

on:
  - pull_request

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
      with:
        # checkout full tree
        fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[dev]
    - name: Testing the code with pytest
      run: |
        python -m pytest --cov=lifecycle --cov-report=term --cov-report=xml
        cat coverage.xml
        coverage report --fail-under=80
  smoketest:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
      with:
        # checkout full tree
        fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Make sure lifecycle can be installed and run using pipenv
      run: |
        python -m pip install pipenv
        pipenv install --skip-lock
        pipenv run lifecycle --help
